# Generated by Django 4.1.13 on 2024-08-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('registered_by', models.IntegerField()),
                ('approved_by', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('serie', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('under_review', 'Under Review')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
