# Generated by Django 4.1.13 on 2024-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='approved_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='registered_by',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serie',
            field=models.BigIntegerField(),
        ),
    ]
