# Generated by Django 4.1.13 on 2024-08-19 17:12

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_approved_by_alter_inventory_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='approved_by',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=djongo.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=djongo.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='registered_by',
            field=djongo.models.fields.JSONField(),
        ),
    ]
